// Copyright (c) 2013-2014 Vittorio Romeo
// License: Academic Free License ("AFL") v. 3.0
// AFL License page: http://opensource.org/licenses/AFL-3.0

#ifndef SSVU_PREPROCESSOR_CONCAT
#define SSVU_PREPROCESSOR_CONCAT

#include <SSVUtils/Preprocessor/Utils.hpp>

namespace ssvu
{
	#define SSVU_PP_IMPL_CONCAT_0(...)			SSVU_PP_EMPTY()
	#define SSVU_PP_IMPL_CONCAT_1(m0, ...)		SSVU_PP_EXPAND(m0)
	#define SSVU_PP_IMPL_CONCAT_2(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_1(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_3(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_2(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_4(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_3(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_5(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_4(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_6(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_5(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_7(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_6(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_8(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_7(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_9(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_8(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_10(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_9(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_11(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_10(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_12(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_11(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_13(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_12(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_14(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_13(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_15(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_14(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_16(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_15(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_17(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_16(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_18(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_17(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_19(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_18(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_20(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_19(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_21(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_20(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_22(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_21(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_23(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_22(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_24(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_23(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_25(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_24(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_26(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_25(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_27(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_26(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_28(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_27(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_29(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_28(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_30(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_29(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_31(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_30(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_32(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_31(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_33(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_32(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_34(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_33(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_35(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_34(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_36(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_35(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_37(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_36(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_38(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_37(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_39(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_38(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_40(m0, m1, ...)	SSVU_PP_IMPL_CONCAT_39(SSVU_PP_TOKENPASTE_2(m0, m1), __VA_ARGS__)

	#define SSVU_PP_IMPL_CONCAT_REVERSE_SEQUENCE()	SSVU_PP_IMPL_CONCAT_40, \
													SSVU_PP_IMPL_CONCAT_39, \
													SSVU_PP_IMPL_CONCAT_38, \
													SSVU_PP_IMPL_CONCAT_37, \
													SSVU_PP_IMPL_CONCAT_36, \
													SSVU_PP_IMPL_CONCAT_35, \
													SSVU_PP_IMPL_CONCAT_34, \
													SSVU_PP_IMPL_CONCAT_33, \
													SSVU_PP_IMPL_CONCAT_32, \
													SSVU_PP_IMPL_CONCAT_31, \
													SSVU_PP_IMPL_CONCAT_30, \
													SSVU_PP_IMPL_CONCAT_29, \
													SSVU_PP_IMPL_CONCAT_28, \
													SSVU_PP_IMPL_CONCAT_27, \
													SSVU_PP_IMPL_CONCAT_26, \
													SSVU_PP_IMPL_CONCAT_25, \
													SSVU_PP_IMPL_CONCAT_24, \
													SSVU_PP_IMPL_CONCAT_23, \
													SSVU_PP_IMPL_CONCAT_22, \
													SSVU_PP_IMPL_CONCAT_21, \
													SSVU_PP_IMPL_CONCAT_20, \
													SSVU_PP_IMPL_CONCAT_19, \
													SSVU_PP_IMPL_CONCAT_18, \
													SSVU_PP_IMPL_CONCAT_17, \
													SSVU_PP_IMPL_CONCAT_16, \
													SSVU_PP_IMPL_CONCAT_15, \
													SSVU_PP_IMPL_CONCAT_14, \
													SSVU_PP_IMPL_CONCAT_13, \
													SSVU_PP_IMPL_CONCAT_12, \
													SSVU_PP_IMPL_CONCAT_11, \
													SSVU_PP_IMPL_CONCAT_10, \
													SSVU_PP_IMPL_CONCAT_9, \
													SSVU_PP_IMPL_CONCAT_8, \
													SSVU_PP_IMPL_CONCAT_7, \
													SSVU_PP_IMPL_CONCAT_6, \
													SSVU_PP_IMPL_CONCAT_5, \
													SSVU_PP_IMPL_CONCAT_4, \
													SSVU_PP_IMPL_CONCAT_3, \
													SSVU_PP_IMPL_CONCAT_2, \
													SSVU_PP_IMPL_CONCAT_1, \
													SSVU_PP_IMPL_CONCAT_0

	#define SSVU_PP_IMPL_CONCAT_DISPATCH_IMPL(	m01, m02, m03, m04, m05, m06, m07, m08, m09, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, \
												m21, m22, m23, m24, m25, m26, m27, m28, m29, m30, m31, m32, m33, m34, m35, m36, m37, m38, m39, m40, mN, ...) mN

	#define SSVU_PP_IMPL_CONCAT_DISPATCH(...)	SSVU_PP_IMPL_CONCAT_DISPATCH_IMPL(__VA_ARGS__)
	#define SSVU_PP_IMPL_CONCAT_IMPL(...)		SSVU_PP_IMPL_CONCAT_DISPATCH(__VA_ARGS__, SSVU_PP_IMPL_CONCAT_REVERSE_SEQUENCE()) (__VA_ARGS__)

	#define SSVU_PP_CONCAT(...)					SSVU_PP_IMPL_CONCAT_IMPL(__VA_ARGS__)
}

#endif

// TODO: comma separated list
