// Copyright (c) 2013-2014 Vittorio Romeo
// License: Academic Free License ("AFL") v. 3.0
// AFL License page: http://opensource.org/licenses/AFL-3.0

#ifndef SSVU_PREPROCESSOR_TUPLE
#define SSVU_PREPROCESSOR_TUPLE

#include "SSVUtils/Preprocessor/VarArgsCount.hpp"
#include "SSVUtils/Preprocessor/Utils.hpp"

namespace ssvu
{
	#define SSVU_PP_IMPL_TPL_GET_0(m0, ...) m0
	#define SSVU_PP_IMPL_TPL_GET_1(m0, m1, ...) m1
	#define SSVU_PP_IMPL_TPL_GET_2(m0, m1, m2, ...) m2
	#define SSVU_PP_IMPL_TPL_GET_3(m0, m1, m2, m3, ...) m3
	#define SSVU_PP_IMPL_TPL_GET_4(m0, m1, m2, m3, m4, ...) m4
	#define SSVU_PP_IMPL_TPL_GET_5(m0, m1, m2, m3, m4, m5, ...) m5
	#define SSVU_PP_IMPL_TPL_GET_6(m0, m1, m2, m3, m4, m5, m6, ...) m6
	#define SSVU_PP_IMPL_TPL_GET_7(m0, m1, m2, m3, m4, m5, m6, m7, ...) m7
	#define SSVU_PP_IMPL_TPL_GET_8(m0, m1, m2, m3, m4, m5, m6, m7, m8, ...) m8
	#define SSVU_PP_IMPL_TPL_GET_9(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, ...) m9
	#define SSVU_PP_IMPL_TPL_GET_10(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, ...) m10
	#define SSVU_PP_IMPL_TPL_GET_11(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, ...) m11
	#define SSVU_PP_IMPL_TPL_GET_12(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, ...) m12
	#define SSVU_PP_IMPL_TPL_GET_13(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, ...) m13
	#define SSVU_PP_IMPL_TPL_GET_14(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, ...) m14
	#define SSVU_PP_IMPL_TPL_GET_15(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, ...) m15
	#define SSVU_PP_IMPL_TPL_GET_16(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, ...) m16
	#define SSVU_PP_IMPL_TPL_GET_17(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, ...) m17
	#define SSVU_PP_IMPL_TPL_GET_18(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, ...) m18
	#define SSVU_PP_IMPL_TPL_GET_19(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, ...) m19
	#define SSVU_PP_IMPL_TPL_GET_20(m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20...) m20

	#define SSVU_PP_IMPL_TPL_GET(mIdx, mTpl)	SSVU_PP_TOKENPASTE_2(SSVU_PP_IMPL_TPL_GET_, mIdx) mTpl
	#define SSVU_PP_TPL_GET(mIdx, mTpl)			SSVU_PP_IMPL_TPL_GET(mIdx, mTpl)

	#define SSVU_PP_IMPL_TPL_MAKE(...)			(__VA_ARGS__)
	#define SSVU_PP_TPL_MAKE(...)				SSVU_PP_IMPL_TPL_MAKE(__VA_ARGS__)

	#define SSVU_PP_IMPL_TPL_EXPLODE(...)		__VA_ARGS__
	#define SSVU_PP_TPL_EXPLODE(mTpl)			SSVU_PP_EXPAND(SSVU_PP_IMPL_TPL_EXPLODE mTpl)



	#define SSVU_PP_IMPL_TPL_CAT_0(...)				SSVU_PP_EMPTY()
	#define SSVU_PP_IMPL_TPL_CAT_1(m0, ...)			m0
	#define SSVU_PP_IMPL_TPL_CAT_2(m0, m1, ...)		SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1))
	#define SSVU_PP_IMPL_TPL_CAT_3(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_2(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_4(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_3(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_5(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_4(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_6(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_5(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_7(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_6(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_8(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_7(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_9(m0, m1, ...)		SSVU_PP_IMPL_TPL_CAT_8(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_10(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_9(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_11(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_10(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_12(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_11(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_13(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_12(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_14(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_13(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_15(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_14(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_16(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_15(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_17(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_16(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_18(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_17(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_19(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_18(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_20(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_19(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_21(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_20(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_22(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_21(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_23(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_22(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_24(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_23(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_25(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_24(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_26(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_25(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_27(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_26(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_28(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_27(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_29(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_28(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_30(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_29(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_31(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_30(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_32(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_31(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_33(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_32(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_34(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_33(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_35(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_34(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_36(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_35(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_37(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_36(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_38(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_37(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_39(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_38(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)
	#define SSVU_PP_IMPL_TPL_CAT_40(m0, m1, ...)	SSVU_PP_IMPL_TPL_CAT_39(SSVU_PP_TPL_MAKE(SSVU_PP_TPL_EXPLODE(m0), SSVU_PP_TPL_EXPLODE(m1)), __VA_ARGS__)

	#define SSVU_PP_IMPL_TPL_CAT_REVERSE_SEQUENCE()	40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, \
													20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1, \
													 0

	#define SSVU_PP_IMPL_TPL_CAT_DISPATCH_IMPL(	m01, m02, m03, m04, m05, m06, m07, m08, m09, m10, m11, m12, m13, m14, m15, m16, m17, m18, m19, m20, \
												m21, m22, m23, m24, m25, m26, m27, m28, m29, m30, m31, m32, m33, m34, m35, m36, m37, m38, m39, m40, \
												mN, ...) SSVU_PP_TOKENPASTE_2(SSVU_PP_IMPL_TPL_CAT_, mN)

	#define SSVU_PP_IMPL_TPL_CAT_DISPATCH(...)	SSVU_PP_IMPL_TPL_CAT_DISPATCH_IMPL(__VA_ARGS__)

	#define SSVU_PP_IMPL_TPL_CAT(...)			SSVU_PP_IMPL_TPL_CAT_DISPATCH(__VA_ARGS__, SSVU_PP_IMPL_TPL_CAT_REVERSE_SEQUENCE()) (__VA_ARGS__)
	#define SSVU_PP_TPL_CAT(...)				SSVU_PP_IMPL_TPL_CAT(__VA_ARGS__)

	#define SSVU_PP_TPL_SIZE(mTpl)				SSVU_PP_VA_NUM_ARGS(SSVU_PP_TPL_EXPLODE(mTpl))
}

#endif
