// Copyright (c) 2013-2014 Vittorio Romeo
// License: Academic Free License ("AFL") v. 3.0
// AFL License page: http://opensource.org/licenses/AFL-3.0

#ifndef SSVU_CORE_PREPROCESSOR_ARGCOUNT
#define SSVU_CORE_PREPROCESSOR_ARGCOUNT

#define SSVPP_IMPL_N_ARG(...)			SSVPP_IMPL_NSEQ(__VA_ARGS__)

#define SSVPP_IMPL_NARGS_COMMA(...)		,
#define SSVPP_IMPL_NARGS_HASCOMMA(...)	SSVPP_IMPL_N_ARG(__VA_ARGS__, SSVPP_IMPL_CSEQ())

#define SSVPP_IMPL_NARGS_DISPATCH_3_01(mN)	0
#define SSVPP_IMPL_NARGS_DISPATCH_3_00(mN)	1
#define SSVPP_IMPL_NARGS_DISPATCH_3_11(mN)	mN

#define SSVPP_IMPL_NARGS_DISPATCH_2(mA, mB, mN)	SSVPP_IMPL_NARGS_DISPATCH_3_ ## mA ## mB(mN)
#define SSVPP_IMPL_NARGS_DISPATCH_1(mA, mB, mN)	SSVPP_IMPL_NARGS_DISPATCH_2(mA, mB, mN)

#define SSVPP_IMPL_ARGCOUNT(...)	SSVPP_IMPL_NARGS_DISPATCH_1(SSVPP_IMPL_NARGS_HASCOMMA(__VA_ARGS__), SSVPP_IMPL_NARGS_HASCOMMA(SSVPP_IMPL_NARGS_COMMA __VA_ARGS__ ()), SSVPP_IMPL_N_ARG(__VA_ARGS__, SSVPP_IMPL_RSEQ()))
#define SSVPP_ARGCOUNT(...)			SSVPP_IMPL_ARGCOUNT(__VA_ARGS__)

#endif
