// Copyright (c) 2013-2014 Vittorio Romeo
// License: Academic Free License ("AFL") v. 3.0
// AFL License page: http://opensource.org/licenses/AFL-3.0

#ifndef SSVU_CORE_PREPROCESSOR_TUPLE
#define SSVU_CORE_PREPROCESSOR_TUPLE

#include "SSVUtils/Core/Preprocessor/Utils.hpp"

#define SSVPP_IMPL_TPL_EXPLODE(...)	__VA_ARGS__
#define SSVPP_IMPL_TPL_MAKE(...)	(__VA_ARGS__)

#define SSVPP_TPL_EXPLODE(mTpl)		SSVPP_EXPAND(SSVPP_IMPL_TPL_EXPLODE mTpl)
#define SSVPP_TPL_MAKE(...)			SSVPP_IMPL_TPL_MAKE(__VA_ARGS__)

#define SSVPP_TPL_FILL_IMPL(mTpl)				SSVPP_TKNCAT_2(SSVPP_IMPL_TPL_FILL_, SSVPP_TPL_SIZE(mTpl)) (mTpl)
#define SSVPP_TPL_FILL_REVERSE_IMPL(mTpl)		SSVPP_TKNCAT_2(SSVPP_IMPL_TPL_FILL_REVERSE_, SSVPP_TPL_SIZE(mTpl)) (mTpl)
#define SSVPP_IMPL_TPL_ELEM(mTpl, mIdx)			SSVPP_TKNCAT_2(SSVPP_IMPL_TPL_ELEM_, mIdx) SSVPP_EXPAND(SSVPP_TPL_FILL(mTpl))
#define SSVPP_IMPL_TPL_ELEM_REVERSE(mTpl, mIdx)	SSVPP_TKNCAT_2(SSVPP_IMPL_TPL_ELEM_REVERSE_, mIdx) SSVPP_EXPAND(SSVPP_TPL_FILL_REVERSE(mTpl))
#define SSVPP_IMPL_TPL_CAT(...)					SSVPP_TKNCAT_2(SSVPP_IMPL_TPL_CAT_, SSVPP_ARGCOUNT(__VA_ARGS__)) (__VA_ARGS__)
#define SSVPP_IMPL_TPL_SIZE(mTpl)				SSVPP_ARGCOUNT(SSVPP_TPL_EXPLODE(mTpl))
#define SSVPP_IMPL_TPL_HEAD(mTpl)				SSVPP_EXPAND(SSVPP_TPL_ELEM(mTpl, 0))
#define SSVPP_IMPL_TPL_TAIL(mTpl)				SSVPP_EXPAND(SSVPP_TPL_ELEM_REVERSE(mTpl, 0))
#define SSVPP_IMPL_TPL_PUSH_BACK(mTpl, mArg)	SSVPP_EXPAND(SSVPP_TPL_MAKE(SSVPP_TPL_EXPLODE(mTpl), mArg))
#define SSVPP_IMPL_TPL_PUSH_FRONT(mTpl, mArg)	SSVPP_EXPAND(SSVPP_TPL_MAKE(mArg, SSVPP_TPL_EXPLODE(mTpl)))

#define SSVPP_TPL_FILL(mTpl)				( SSVPP_TPL_FILL_IMPL(mTpl) )
#define SSVPP_TPL_FILL_REVERSE(mTpl)		( SSVPP_TPL_FILL_REVERSE_IMPL(mTpl) )
#define SSVPP_TPL_ELEM(mTpl, mIdx)			SSVPP_EXPAND(SSVPP_IMPL_TPL_ELEM(mTpl, mIdx))
#define SSVPP_TPL_ELEM_REVERSE(mTpl, mIdx)	SSVPP_EXPAND(SSVPP_IMPL_TPL_ELEM_REVERSE(mTpl, mIdx))
#define SSVPP_TPL_CAT(...)					SSVPP_IMPL_TPL_CAT(__VA_ARGS__)
#define SSVPP_TPL_SIZE(mTpl)				SSVPP_IMPL_TPL_SIZE(mTpl)
#define SSVPP_TPL_HEAD(mTpl)				SSVPP_IMPL_TPL_HEAD(mTpl)
#define SSVPP_TPL_TAIL(mTpl)				SSVPP_IMPL_TPL_TAIL(mTpl)
#define SSVPP_TPL_PUSH_BACK(mTpl, mArg)		SSVPP_IMPL_TPL_PUSH_BACK(mTpl, mArg)
#define SSVPP_TPL_PUSH_FRONT(mTpl, mArg)	SSVPP_IMPL_TPL_PUSH_FRONT(mTpl, mArg)

#endif
