FIND_PATH(SSVUTILS_INCLUDE_DIR
	NAMES SSVUtils/SSVUtils.h
	PATH_SUFFIXES include/
	PATHS "${PROJECT_SOURCE_DIR}/../SSVUtils/"
	"${PROJECT_SOURCE_DIR}/extlibs/SSVUtils/"
	${SSVUTILS_ROOT}
	$ENV{SSVUTILS_ROOT}
	/usr/local/
	/usr/
	/sw/
	/opt/local/
	/opt/csw/
	/opt/
)

MESSAGE("\nFound SSVUtils include at: ${SSVUTILS_INCLUDE_DIR}.\n")

FIND_LIBRARY(SSVUTILS_LIBRARY
	NAMES SSVUtils libSSVUtils SSVUtils-s libSSVUtils-s ssvutils libssvutils ssvutils-s libssvutils-s
	PATH_SUFFIXES lib/ lib64/
	PATHS "${PROJECT_SOURCE_DIR}/../SSVUtils/"
	"${PROJECT_SOURCE_DIR}/extlibs/SSVUtils/"
	${SSVUTILS_ROOT}
	$ENV{SSVUTILS_ROOT}
	/usr/local/
	/usr/
	/sw/
	/opt/local/
	/opt/csw/
	/opt/
)

MESSAGE("\nFound SSVUtils library at: ${SSVUTILS_LIBRARY}.\n")

IF(SSVUTILS_LIBRARY AND SSVUTILS_INCLUDE_DIR)
	SET(SSVUTILS_LIBRARIES ${SSVUTILS_LIBRARY})
	SET(SSVUTILS_FOUND TRUE)
ELSE(SSVUTILS_LIBRARY AND SSVUTILS_INCLUDE_DIR)
	SET(SSVUTILS_FOUND FALSE)
ENDIF(SSVUTILS_LIBRARY AND SSVUTILS_INCLUDE_DIR)

IF(SSVUTILS_FOUND)
	MESSAGE(STATUS "\nFound SSVUTILS: ${SSVUTILS_LIBRARIES}\n")
ELSE(SSVUTILS_FOUND)
	IF(SSVUTILS_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "\nCould not find SSVUtils library\n")
	ENDIF(SSVUTILS_FIND_REQUIRED)
ENDIF(SSVUTILS_FOUND)

MARK_AS_ADVANCED(
	SSVUTILS_LIBRARY
	SSVUTILS_INCLUDE_DIR
)
